### ISSUE TITLE
Enhance flags/emojis legends description

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#15]
As requested by one the user of nsecure (member of the ES Community) it would be could to work around the description of each flags (both in the UI and in the README.md).

The current UI take to match place because there is to much flags (so there is a need to rethink how we can deal with this without having to scroll).

![](https://i.imgur.com/vG6ixWr.png)

Maybe only showing the title and having to click to show the description (an idea).

> Note: more flags will come with the time.

And it would be cool to show the flag description on hover in the left show info menu (when we are checking a package flags).

![](https://i.imgur.com/5H0OKbX.png)

**Comment by Xstoudi** [comment]
I think the view on the first screenshot should be in a modal that opens when we click on something like "Flags legend" and a short description should appear as a tooltip when we hover the flags shown in the second screenshot.

**Comment by fraxken** [comment]
- FLAGS.md done
- Flag description on hover done by @CroquetMickael 

Remain the new emojis legends modal !

**Comment by fraxken** [comment]
Done.
