### ISSUE TITLE
Node.js random ENOENT in processPackageTarball

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#16]
The method processPackageTarball in depWalker.js fail a lot of time randomly with some Node.js ENOENT (No entry). But if we check closer these files exist at the moment so there is a problem...

Example of a run with express:
```
$ nsecure from express -d 10

 > Executing node-secure at: F:\Code 

√ Fetched express manifest on npm in 162.69 ms
⠼ Fetching all dependencies ...
[Error: ENOENT: no such file or directory, open 'C:\Users\tgent\AppData\Local\Temp\0fc95b05\safe-buffer@5.1.2\package.json'] { 
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\tgent\\AppData\\Local\\Temp\\0fc95b05\\safe-buffer@5.1.2\\package.json'
⠦ Fetching all dependencies ...
[Error: ENOENT: no such file or directory, open 'C:\Users\tgent\AppData\Local\Temp\0fc95b05\depd@1.1.2\package.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\tgent\\AppData\\Local\\Temp\\0fc95b05\\depd@1.1.2\\package.json'
⠧ Fetching all dependencies ...
[Error: ENOENT: no such file or directory, open 'C:\Users\tgent\AppData\Local\Temp\0fc95b05\debug@2.6.9\package.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\tgent\\AppData\\Local\\Temp\\0fc95b05\\debug@2.6.9\\package.json'
}
[Error: ENOENT: no such file or directory, open 'C:\Users\tgent\AppData\Local\Temp\0fc95b05\on-finished@2.3.0\package.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\tgent\\AppData\\Local\\Temp\\0fc95b05\\on-finished@2.3.0\\package.json'
⠸ Fetching all dependencies ...
[Error: ENOENT: no such file or directory, open 'C:\Users\tgent\AppData\Local\Temp\0fc95b05\statuses@1.5.0\package.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\tgent\\AppData\\Local\\Temp\\0fc95b05\\statuses@1.5.0\\package.json'
√ Successfully fetched and processed all stats in 4047.48 ms

Sucessfully result .json file at: F:\Code\result.json
```

These errors occur a lot of time for open (package.json) but occur for stat or opendir too. By default the catch doesn't console.log the err (it will ignore).

So if you want to be able to show the error you have to update the code here:
https://github.com/ES-Community/nsecure/blob/master/src/depWalker.js#L216

**Comment by targos** [comment]
Do you know why it happens?

**Comment by fraxken** [comment]
No idea. But in the case of open for package.json it almost always fail the second time we read the package.json.

first here: https://github.com/ES-Community/nsecure/blob/master/src/depWalker.js#L154
second time here: https://github.com/ES-Community/nsecure/blob/master/src/depWalker.js#L210 (in the package i created to retrieve license).

So i guess there is a maybe a "lock" problem or something similar or maybe a mistake on how we deal with these files (not sure).

**Comment by fraxken** [comment]
The problem seem to disappear when we set maxConcurrent to 5 (for the tarballLocker). However still have one error time to time (but with 25 i have almost 4-5 errors for each run).
