### ISSUE TITLE
Ajout d'une légende dans l'interface

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#2]
Ajout d'un onglet dans l'interface pour afficher la légende des flags avec les différents emojis. Pour le moment voici la liste complète:

🌍 Le package possède des dépendances indirectes.
⚠️ Le package possède des imports suspect.
💎 Le package possède des dépendances qui ne sont pas des packages ( file, +git etc..).
📜 Le package ne semble pas avoir de license
🔬 Le package semble avoir des fichiers qui sont minifiés/uglifiés. 
⛔️ Le package est deprecated
💕 Le package possède plusieurs publishers
👥 L'auteur du package à déjà changé au moins une fois (Ce n'est pas un flag spécialement fiable).

Le mieux serait d'ajouter le dit menu au-dessus de la section de description des projets
![](https://i.imgur.com/A9VFAh1.png)

Par exemple avec le texte suivant:
⭐️ Légendes

Et lors d'un hover: affiché toutes les informations (laisser toutes les légendes affichées prendrait sûrement trop de place/visibilité.. Enfin sujet à éventuellement débattre).

Uniquement du HTML / CSS ici (normalement).

**Comment by Kawacrepe** [comment]
Hello,

Est-ce un choix de n'utiliser aucun fw pour le front ?
