### ISSUE TITLE
add contributors

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#22]
@all-contributors please add @fraxken  for code,bug,blog,test,doc,design

**Comment by fraxken** [comment]
@all-contributors please add @CroquetMickael for code, design

**Comment by fraxken** [comment]
@all-contributors please add @fraxken for code, bug, blog, test, doc, design

**Comment by Xstoudi** [comment]
@all-contributors please add @Xstoudi for code, design, doc
