### ISSUE TITLE
Dockerfile ?

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#23]
It would be cool to create a Dockerfile to be able to use the CLI in a container for those without a proper Node.js environment.

**Comment by targos** [comment]
How would you use such a Docker image?

**Comment by fraxken** [comment]
I'm not using that much Docker for that kind of things but this seem to be possible to use the tool with it.

- https://github.com/lirantal/nodejs-cli-apps-best-practices#41-containerize-the-cli
- https://janikarhunen.fi/run-nodejs-cli-tools-in-docker-container

I guess we can take a look at some of the Lirantal CLI Dockerfile tool:
- https://github.com/lirantal/is-website-vulnerable/blob/master/Dockerfile
OR
- https://github.com/lirantal/pie-my-vulns/pull/28/files
