### ISSUE TITLE
Update dependency 'vis'

### ISSUE THREAD

**Issue by mojoaxel** [ES-Community/nsecure#38]
You are still using a very outdated version 4.21 of vis.
This version is not supported anymore!

Please update to the new libraries:
https://github.com/visjs

Feel free to contact us if you need any support during the transition :-)

**Comment by fraxken** [comment]
Hi, thanks for the issue.

Should be done with this commit: dhttps://github.com/ES-Community/nsecure/commit/d0db811234ebe5b40f0aa0035cd2bdd4d7c51d84
