### ISSUE TITLE
Emoji icons

### ISSUE THREAD

**Issue by kumavis** [ES-Community/nsecure#39]
"performing arts" masks ( :performing_arts: )
is shown in the graph view but not in the detail view and not defined in the "emoji legends" section

**Comment by kumavis** [comment]
![image](https://user-images.githubusercontent.com/1474978/82863561-0ac5e780-9f55-11ea-846e-0e4a0fc8edcc.png)

**Comment by fraxken** [comment]
Hi,

Yep this is the only "special" emoji, check the doc here for info: https://github.com/ES-Community/nsecure/blob/master/FLAGS.md#web-ui-emojis

I have to found a proper way to implement this emoji as well in the legends.

**Comment by fraxken** [comment]
fixed on master branch:
