### ISSUE TITLE
Log global warnings to the Stdout

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#46]
In Node-secure we have what we call "global" warnings for some dangerous packages: https://github.com/ES-Community/nsecure/blob/master/src/warnings.js#L9

On the UI those warnings are here:
![](https://i.imgur.com/kD5fQwO.png)

It would be cool to log all warnings to the CLI stdout as well to be sure the user don't miss them.

Logs could be done after this line: https://github.com/ES-Community/nsecure/blob/master/src/depWalker.js#L496

**Comment by CroquetMickael** [comment]
Hey there, any package to test the feature with one or both package ? :)

**Comment by fraxken** [comment]
just create a local project with them as dependencies ^^

**Comment by CroquetMickael** [comment]
Well, completly forgot that you can scan a project, I will do it today :)

**Comment by fraxken** [comment]
Thanks for the contribution!
