### ISSUE TITLE
Searchbar - next ?

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#50]
The current search bar work properly (I wouldn't say there aren't some bugs either ^^). However several features are still missing:

- Search history (like Discord search bar).
- Unable to search for flags related to the metadata etc (these informations are not on the linker).
- Better presentation of the packages found? (Like when we search package of a given size.. we should display the size of the packages in the result).
- Maybe do not erase immediatly the search when we click outside ?
- The design can certainly still be improved

Optimizing and making the code more maintainable is surely also a long term goal.

> If any of you think you can improve all of this then feel free to open a PR.

**Comment by Kawacrepe** [comment]
Hello !

Can I pick this task and get guidance on how contribute ?
Maybe it would be interesting to compile informations onto a contributing.md, commit standards, branch name, how run the project during development...

**Comment by fraxken** [comment]
A better search bar will be integrated on version 2 of the UI.
