### ISSUE TITLE
Windows Powershell not fount

### ISSUE THREAD

**Issue by RemyTinco** [ES-Community/nsecure#54]
## Current behavior
When I'm doing a `nsecure auto`, my packages are analyzed but the CLI exited with an error because of ENOENT powershell :/ 

```YAML
✔ Successfully navigated through the dependency tree in 19s
✔ Successfully analyzed 1727 packages tarball in 2m
✔ Successfully fetched required metadata for all packages!

Successfully written .json file at: /home/remy/mansa/nsecure-result.json
HTTP Server started http://localhost:40655
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn powershell.exe',
  path: 'powershell.exe',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBgACIAaAB0AHQAcAA6AC8ALwBsAG8AYwBhAGwAaABvAHMAdAA6ADQAMAA2ADUANQBgACIAIgA='
  ]
}
``` 

## Expected behavior
When I'm doing a `nsecure auto`, with already a `nsecure-result.json` successfully generated, I expect the web visualization.

**Others:**

Nsecure version 0.4.0
I'm currently in an Ubuntu subsystem on my Windows 10

**Comment by fraxken** [comment]
Seem to be an issue with the [open](https://github.com/sindresorhus/open) package on WSL. Since 7.2.0 they use powershell instead of cmd on Windows.

**Comment by fraxken** [comment]
Need to be tested with the latest next release. I upgraded open to 7.3.0 and this release seem to include a fix for WSL probably related to the issue.

**Comment by fraxken** [comment]
I close the issue. Feel free to MP me to re-open if the bug still appear.
