### ISSUE TITLE
Remove flags with "false" value from the JSON payload

### ISSUE THREAD

**Issue by fraxken** [ES-Community/nsecure#58]
Remove all the flags with `false` value from the JSON payload to not keep to much data on disk and on memory.

![](https://media.discordapp.net/attachments/755759500652183643/773462168255332362/unknown.png)
to

![](https://media.discordapp.net/attachments/755759500652183643/773462363524956160/unknown.png)

**Comment by targos** [comment]
If the list becomes only the ones with `true`, it could be an Array.

**Comment by tony-go** [comment]
I take it ^^ If it's okay for you?

**Comment by fraxken** [comment]
Implemented on master.
