### ISSUE TITLE
Add an history to the searchbar

### ISSUE THREAD

**Issue by Kawacrepe** [ES-Community/nsecure#77]
Hello,

I just go through trello and see a [task](https://trello.com/c/Uft5DB45/5-add-an-history-to-the-searchbar-like-discord). which can help me to get into the project.
Can I get any guidance on how contributing to the project ?

**Comment by tony-go** [comment]
Hi @Kawacrepe 👋 

Hope you're doing well ?

I think there is an issue on this already -> #50 

CC @fraxken

**Comment by Kawacrepe** [comment]
oh sorry, it's a duplicate.
I close this one
