### ISSUE TITLE
nsecure open

### ISSUE THREAD

**Issue by NieZhuZhu** [ES-Community/nsecure#87]
Waiting too long, it never loaded out. There are only 162 packages.
![image](https://user-images.githubusercontent.com/44939961/133118967-6206beb1-ac2f-43ee-8294-80c68f2ee36b.png)
![image](https://user-images.githubusercontent.com/44939961/133118830-17bd403b-fa5d-4894-b4b3-ffdf224679cc.png)

node version : v14.17.0

**Comment by tony-go** [comment]
Hi @NieZhuZhu 👋 

Thanks for reporting. 

I think that without more information, It'll be hard to invest in this bug.

Maybe could you provide us a reproducible example (a package.json is enough)?

**Comment by fraxken** [comment]
The old version had a problem with the automatic opening (probably related). Version 0.9.0 is available so i close this issue.
