### ISSUE TITLE
missing declared dependency (for pnpm compatibility)

### ISSUE THREAD

**Issue by dcaillibaud** [ES-Community/nsecure#96]
Hi,

I'm using pnpm as package manager, and installing nsecure (0.9.1) with it leads to a failure

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'timers' imported from /usr/pnpm-global/5/node_modules/.pnpm/@nodesecure+scanner@3.2.1/node_modules/@nodesecure/scanner/index.js
```

I guess that `timers` is [missing in scanner dependencies](https://pnpm.io/faq#pnpm-does-not-work-with-your-project-here) (it works on npm and yarn because of flat dependencies tree, because timers should be a dependency of a scanner dependency).

**Comment by fraxken** [comment]
`timers` is core Node.js dependencies.https://nodejs.org/dist/latest-v16.x/docs/api/timers.html

**Comment by fraxken** [comment]
There are probably problems with pnpm anyway. I am not very familiar with it so I would have to look into it.

**Comment by dcaillibaud** [comment]
Ok, I'm running node 14 (because our production servers are running this version), which contains [timers](https://nodejs.org/dist/latest-v14.x/docs/api/timers.html) but not [timers/promise](https://nodejs.org/docs/latest-v16.x/api/timers.html#timers-promises-api) required by `@nodesecure/scanner`

So it should be a bug in pnpm because it doesn't complain on installing nsecure (and `"node": ">=16.1.0"` is mentioned in nsecure package.json).

Sorry for the noise, thanks for the quick answer.

**Comment by fraxken** [comment]
@dcaillibaud No problems 👌.
